// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/dna_blog_version.test.ts.

/** The version of the `@ggdna/dna-blog` package. */
export const dnaBlogVersion = '0.1.1';
